### ISSUE TITLE
No imu_mobile_base link in stretch_description

### ISSUE THREAD

**Issue by marekmlk** [hello-robot/stretch_ros#118]
Hello,
mobile base IMU and magnetometer topics frame is `imu_mobile_base` but it is not available in `stretch_description`. Can you add it? Or just post translation and orientation wrt to `base_link` or `base_footprint`...
Regards,
Marek

**Comment by hello-binit** [comment]
Hi Marek, thanks for opening this issue. I will look into this.

**Comment by hello-binit** [comment]
Hi @marekmlk, pulling the latest code on the 'noetic' branch and rebuilding your URDF should now result in a URDF that includes the frame for the IMU in the mobile base.

**Comment by marekmlk** [comment]
I saw it ! Thanks a lot!
