### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by SteveMacenski** [hello-robot/stretch_ros#28]
Hi,

A colleague and I are writing a robotics book centralized around the theme about how to make "actual" robots work in the "actual" world containing content on mobile, manipulation, perception, and architecture. We need a mobile-manipulator robot to centralized around for all of the chapters of the book and we are considering Stretch. However, we require this book to be in ROS2 and we don't see a ROS2 branch / support. Is this something that is in the works or will be released in the near-term future?

**Comment by hello-binit** [comment]
Hi @SteveMacenski, glad to hear you're considering Stretch. Sounds like a good fit. We've partnered with PickNik Robotics to bring ROS2 and MoveIt2 support to Stretch (see the [announcement here](https://picknik.ai/ros/picknik/hello%20robot/2021/04/22/hello-robot-announcement.html)). On the [ros2 branch](https://github.com/PickNikRobotics/stretch_ros/) of their fork, there is preliminary support for ROS2 Galactic, including a ROS2 version of the stretch_core package. [Stretch_core](https://github.com/PickNikRobotics/stretch_ros/tree/ros2/stretch_core) provides the FollowJointTrajectory action server used by MoveIt/other planners, the "/cmd_vel" topic to perform velocity control on the differential drive mobile base, and other functionality usually found on ROS robots. @DLu from PickNik Robotics leads this ROS2/MoveIt2 effort and has ported much of stretch_core.

Stretch packages like [stretch_calibration](https://github.com/PickNikRobotics/stretch_ros/tree/ros2/stretch_calibration) and [stretch_demos](https://github.com/PickNikRobotics/stretch_ros/tree/ros2/stretch_demos) are not yet ported to ROS2. In the upcoming months, we plan to port these packages and merge the ROS2 support back into our fork. Additionally, a series of MoveIt2 tutorials revolving around mobile manipulation with Stretch and a Ignition simulation of Stretch will be released.

**Comment by hello-binit** [comment]
Stable support for ROS 2 Humble exists in the [Stretch ROS2](https://github.com/hello-robot/stretch_ros2) repo. Future ROS2 development will take place in that repo.
