### ISSUE TITLE
Gazebo simulation?

### ISSUE THREAD

**Issue by msadowski** [hello-robot/stretch_ros#3]
Hi!

I've just learned about your robots and came across your repositories. Many thanks for open sourcing so much of your software stack! I'll most likely feature it in Weekly Robotics sooner or later.

Are you planning to release a gazebo simulation for this platform? I think it would be an interesting learning tool.

**Comment by hello-binit** [comment]
Hi Mat,

It was great to see Hello Robot featured in your newsletter. I've been a reader for some time now. At the moment, a simulation isn't a development focus of the team, but I agree that it would be an interesting learning tool. Keep an eye on our [forum](https://forum.hello-robot.com/) for announcements about this.

Binit

**Comment by hello-binit** [comment]
@msadowski Quick update: we now have a Gazebo simulation of Stretch! See the announcement post [here](https://forum.hello-robot.com/t/stretch-gazebo-simulation-for-melodic-and-noetic/212) and README [here](https://github.com/hello-robot/stretch_ros/blob/master/stretch_gazebo/README.md).
