### ISSUE TITLE
Dexterous gripper STL model license

### ISSUE THREAD

**Issue by knorth55** [hello-robot/stretch_ros#63]
Hello, I'm Shingo Kitagawa at JSK lab, UTokyo.
We got Stretch-RE1 + dexterous gripper, and dexterous gripper STL and urdf is not commited to this repo.
Can we check the license of the uncomitted gripper STL and urdf?
If they are under BSD3 license as same as other STL model, can I make a PR to add dexterous gripper to this repo?
Thank you.

**Comment by hello-binit** [comment]
Hello @knorth55,

Extra tools and grippers for Stretch can be found in the [Stretch Tool Share](https://github.com/hello-robot/stretch_tool_share), licensed as Apache 2.0. The dexterous wrist's [STL and URDF files](https://github.com/hello-robot/stretch_tool_share/tree/master/tool_share/stretch_dex_wrist/stretch_description) are in this tool share. For more information on using the Dex Wrist, take a look at [Dex Wrist User Guide](https://docs.hello-robot.com/dex_wrist_user_guide/).

**Comment by knorth55** [comment]
@hello-binit I didn't know the Stretch Tool Share repo. Thank you!
