### ISSUE TITLE
FUNMAP on Gazebo

### ISSUE THREAD

**Issue by xli4217** [hello-robot/stretch_ros#81]
Hi, I didn't any instructions on this so thought I'd quickly ask - does FUNMAP currently run on Gazebo (sorry for repeating the title)?

**Comment by hello-binit** [comment]
@xli4217 I'm sorry, it only runs on a real Stretch robot currently. This [forum post](https://forum.hello-robot.com/t/is-there-a-way-to-run-funmap-on-gazebo-simulation/288/4?u=bshah) outlines what development would need to happen to be able to run FUNMAP with a Gazebo simulation of Stretch.
