### ISSUE TITLE
Positive linear velocity causes stretch to move backwards in gazebo.

### ISSUE THREAD

**Issue by NateWright** [hello-robot/stretch_ros#87]
Hi, I have been working more with stretch in simulation and have noticed a message like
`rostopic pub -r 60 /stretch_diff_drive_controller/cmd_vel geometry_msgs/Twist "linear:
  x: 0.1
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0"`
will cause the robot to move backwards which I believe is not intentional.
[Screencast from 01-11-2023 04:38:52 PM.webm](https://user-images.githubusercontent.com/51861722/211923976-cad238b0-f22b-46e6-a567-2a36951341be.webm)

**Comment by hello-binit** [comment]
Thanks @NateWright, I'll look into this.

**Comment by hello-fazil** [comment]
@NateWright Thank you for pointing out this issue. We found a bug in the wheel joints URDF definition causing this behavior in the gazebo, which is now rectified with this [push](https://github.com/hello-robot/stretch_ros/commit/31291d4b95a3bda624a40592049a0be592152e41). 
Let us know if you need further help.
